---
- hosts: webservers
  become: true
  become_user: root
  vars:
    src_path= /etc/ansible
    dest_path= /var/www/html
  tasks:
  - name: Install the httpd on webservers
    yum: name=httpd state=present
  - name: Start the httpd services
    service: name=httpd state=started
  - name: Deploy the file
    copy: 
      src:{{src_path}}/index.html
      dest:{{dest_path}}
    notify: restart httpd
  handlers:
  - name: restart httpd
    service: name=httpd state=restarted